// Mocks generated by Mockito 5.4.6 from annotations
// in bagistruk/test/presentation/bills/bill_review_notifier_save_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:bagistruk/core/error/result.dart' as _i4;
import 'package:bagistruk/domain/entities/assignment.dart' as _i10;
import 'package:bagistruk/domain/entities/bill.dart' as _i5;
import 'package:bagistruk/domain/entities/deleted_bill.dart' as _i7;
import 'package:bagistruk/domain/entities/item.dart' as _i8;
import 'package:bagistruk/domain/entities/participant.dart' as _i9;
import 'package:bagistruk/domain/repositories/i_bill_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [IBillRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIBillRepository extends _i1.Mock implements _i2.IBillRepository {
  MockIBillRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.Bill>>> listBills({DateTime? createdAfter}) =>
      (super.noSuchMethod(
            Invocation.method(#listBills, [], {#createdAfter: createdAfter}),
            returnValue: _i3.Future<_i4.Result<List<_i5.Bill>>>.value(
              _i6.dummyValue<_i4.Result<List<_i5.Bill>>>(
                this,
                Invocation.method(#listBills, [], {
                  #createdAfter: createdAfter,
                }),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i5.Bill>>>);

  @override
  _i3.Future<_i4.Result<_i5.Bill>> getBill(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBill, [id]),
            returnValue: _i3.Future<_i4.Result<_i5.Bill>>.value(
              _i6.dummyValue<_i4.Result<_i5.Bill>>(
                this,
                Invocation.method(#getBill, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Bill>>);

  @override
  _i3.Future<_i4.Result<_i5.Bill>> createBill(_i5.Bill? bill) =>
      (super.noSuchMethod(
            Invocation.method(#createBill, [bill]),
            returnValue: _i3.Future<_i4.Result<_i5.Bill>>.value(
              _i6.dummyValue<_i4.Result<_i5.Bill>>(
                this,
                Invocation.method(#createBill, [bill]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Bill>>);

  @override
  _i3.Future<_i4.Result<_i5.Bill>> updateBill(_i5.Bill? bill) =>
      (super.noSuchMethod(
            Invocation.method(#updateBill, [bill]),
            returnValue: _i3.Future<_i4.Result<_i5.Bill>>.value(
              _i6.dummyValue<_i4.Result<_i5.Bill>>(
                this,
                Invocation.method(#updateBill, [bill]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.Bill>>);

  @override
  _i3.Future<_i4.Result<void>> deleteBill(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBill, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteBill, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<void>> restoreDeletedBill(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreDeletedBill, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#restoreDeletedBill, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i7.DeletedBill>>> listDeletedBills() =>
      (super.noSuchMethod(
            Invocation.method(#listDeletedBills, []),
            returnValue: _i3.Future<_i4.Result<List<_i7.DeletedBill>>>.value(
              _i6.dummyValue<_i4.Result<List<_i7.DeletedBill>>>(
                this,
                Invocation.method(#listDeletedBills, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i7.DeletedBill>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.Item>>> listItems(String? billId) =>
      (super.noSuchMethod(
            Invocation.method(#listItems, [billId]),
            returnValue: _i3.Future<_i4.Result<List<_i8.Item>>>.value(
              _i6.dummyValue<_i4.Result<List<_i8.Item>>>(
                this,
                Invocation.method(#listItems, [billId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.Item>>>);

  @override
  _i3.Future<_i4.Result<List<_i8.Item>>> upsertItems(List<_i8.Item>? items) =>
      (super.noSuchMethod(
            Invocation.method(#upsertItems, [items]),
            returnValue: _i3.Future<_i4.Result<List<_i8.Item>>>.value(
              _i6.dummyValue<_i4.Result<List<_i8.Item>>>(
                this,
                Invocation.method(#upsertItems, [items]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i8.Item>>>);

  @override
  _i3.Future<_i4.Result<List<_i9.Participant>>> listParticipants(
    String? billId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listParticipants, [billId]),
            returnValue: _i3.Future<_i4.Result<List<_i9.Participant>>>.value(
              _i6.dummyValue<_i4.Result<List<_i9.Participant>>>(
                this,
                Invocation.method(#listParticipants, [billId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i9.Participant>>>);

  @override
  _i3.Future<_i4.Result<_i9.Participant>> upsertParticipant(
    _i9.Participant? participant,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertParticipant, [participant]),
            returnValue: _i3.Future<_i4.Result<_i9.Participant>>.value(
              _i6.dummyValue<_i4.Result<_i9.Participant>>(
                this,
                Invocation.method(#upsertParticipant, [participant]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i9.Participant>>);

  @override
  _i3.Future<_i4.Result<void>> deleteParticipant(String? participantId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteParticipant, [participantId]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteParticipant, [participantId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);

  @override
  _i3.Future<_i4.Result<List<_i10.Assignment>>> listAssignments(
    String? billId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#listAssignments, [billId]),
            returnValue: _i3.Future<_i4.Result<List<_i10.Assignment>>>.value(
              _i6.dummyValue<_i4.Result<List<_i10.Assignment>>>(
                this,
                Invocation.method(#listAssignments, [billId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i10.Assignment>>>);

  @override
  _i3.Future<_i4.Result<List<_i10.Assignment>>> replaceAssignments(
    String? billId,
    List<_i10.Assignment>? assignments,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replaceAssignments, [billId, assignments]),
            returnValue: _i3.Future<_i4.Result<List<_i10.Assignment>>>.value(
              _i6.dummyValue<_i4.Result<List<_i10.Assignment>>>(
                this,
                Invocation.method(#replaceAssignments, [billId, assignments]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<List<_i10.Assignment>>>);

  @override
  _i3.Future<_i4.Result<void>> ensureSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#ensureSignedIn, []),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i6.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#ensureSignedIn, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
