// Mocks generated by Mockito 5.4.6 from annotations
// in bagistruk/test/data/repositories/repository_contract_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:typed_data' as _i14;

import 'package:bagistruk/core/error/result.dart' as _i8;
import 'package:bagistruk/data/datasources/bill_remote_datasource.dart' as _i6;
import 'package:bagistruk/data/dtos/assignment_dto.dart' as _i11;
import 'package:bagistruk/data/dtos/bill_dto.dart' as _i4;
import 'package:bagistruk/data/dtos/history_bill_page_dto.dart' as _i2;
import 'package:bagistruk/data/dtos/history_summary_dto.dart' as _i3;
import 'package:bagistruk/data/dtos/item_dto.dart' as _i10;
import 'package:bagistruk/data/dtos/ocr_response_dto.dart' as _i13;
import 'package:bagistruk/data/dtos/participant_dto.dart' as _i5;
import 'package:bagistruk/data/services/ocr_service.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHistoryBillPageDto_0 extends _i1.SmartFake
    implements _i2.HistoryBillPageDto {
  _FakeHistoryBillPageDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHistorySummaryDto_1 extends _i1.SmartFake
    implements _i3.HistorySummaryDto {
  _FakeHistorySummaryDto_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBillDto_2 extends _i1.SmartFake implements _i4.BillDto {
  _FakeBillDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeParticipantDto_3 extends _i1.SmartFake
    implements _i5.ParticipantDto {
  _FakeParticipantDto_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [BillRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockBillRemoteDataSource extends _i1.Mock
    implements _i6.BillRemoteDataSource {
  MockBillRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.Result<String>> authEnsureSignedIn() =>
      (super.noSuchMethod(
            Invocation.method(#authEnsureSignedIn, []),
            returnValue: _i7.Future<_i8.Result<String>>.value(
              _i9.dummyValue<_i8.Result<String>>(
                this,
                Invocation.method(#authEnsureSignedIn, []),
              ),
            ),
          )
          as _i7.Future<_i8.Result<String>>);

  @override
  _i7.Future<List<_i4.BillDto>> listBills({DateTime? createdAfter}) =>
      (super.noSuchMethod(
            Invocation.method(#listBills, [], {#createdAfter: createdAfter}),
            returnValue: _i7.Future<List<_i4.BillDto>>.value(<_i4.BillDto>[]),
          )
          as _i7.Future<List<_i4.BillDto>>);

  @override
  _i7.Future<_i2.HistoryBillPageDto> listHistoryBillsPage({
    required DateTime? createdAfter,
    required int? limit,
    required String? sort,
    String? currencyCode,
    String? paymentStatus,
    String? cursorSortValue,
    DateTime? cursorCreatedAt,
    String? cursorId,
    String? query,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listHistoryBillsPage, [], {
              #createdAfter: createdAfter,
              #limit: limit,
              #sort: sort,
              #currencyCode: currencyCode,
              #paymentStatus: paymentStatus,
              #cursorSortValue: cursorSortValue,
              #cursorCreatedAt: cursorCreatedAt,
              #cursorId: cursorId,
              #query: query,
              #category: category,
            }),
            returnValue: _i7.Future<_i2.HistoryBillPageDto>.value(
              _FakeHistoryBillPageDto_0(
                this,
                Invocation.method(#listHistoryBillsPage, [], {
                  #createdAfter: createdAfter,
                  #limit: limit,
                  #sort: sort,
                  #currencyCode: currencyCode,
                  #paymentStatus: paymentStatus,
                  #cursorSortValue: cursorSortValue,
                  #cursorCreatedAt: cursorCreatedAt,
                  #cursorId: cursorId,
                  #query: query,
                  #category: category,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.HistoryBillPageDto>);

  @override
  _i7.Future<_i3.HistorySummaryDto> getHistorySummary({
    required DateTime? createdAfter,
    String? query,
    String? category,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHistorySummary, [], {
              #createdAfter: createdAfter,
              #query: query,
              #category: category,
            }),
            returnValue: _i7.Future<_i3.HistorySummaryDto>.value(
              _FakeHistorySummaryDto_1(
                this,
                Invocation.method(#getHistorySummary, [], {
                  #createdAfter: createdAfter,
                  #query: query,
                  #category: category,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.HistorySummaryDto>);

  @override
  _i7.Future<_i4.BillDto> getBill(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBill, [id]),
            returnValue: _i7.Future<_i4.BillDto>.value(
              _FakeBillDto_2(this, Invocation.method(#getBill, [id])),
            ),
          )
          as _i7.Future<_i4.BillDto>);

  @override
  _i7.Future<int> checkManualBillLimit() =>
      (super.noSuchMethod(
            Invocation.method(#checkManualBillLimit, []),
            returnValue: _i7.Future<int>.value(0),
          )
          as _i7.Future<int>);

  @override
  _i7.Future<_i4.BillDto> upsertBill(_i4.BillDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#upsertBill, [dto]),
            returnValue: _i7.Future<_i4.BillDto>.value(
              _FakeBillDto_2(this, Invocation.method(#upsertBill, [dto])),
            ),
          )
          as _i7.Future<_i4.BillDto>);

  @override
  _i7.Future<void> deleteBill(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBill, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> restoreDeletedBill(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#restoreDeletedBill, [id]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i6.DeletedBillDto>> listDeletedBills() =>
      (super.noSuchMethod(
            Invocation.method(#listDeletedBills, []),
            returnValue: _i7.Future<List<_i6.DeletedBillDto>>.value(
              <_i6.DeletedBillDto>[],
            ),
          )
          as _i7.Future<List<_i6.DeletedBillDto>>);

  @override
  _i7.Future<List<_i10.ItemDto>> listItems(String? billId) =>
      (super.noSuchMethod(
            Invocation.method(#listItems, [billId]),
            returnValue: _i7.Future<List<_i10.ItemDto>>.value(<_i10.ItemDto>[]),
          )
          as _i7.Future<List<_i10.ItemDto>>);

  @override
  _i7.Future<List<_i10.ItemDto>> upsertItems(List<_i10.ItemDto>? items) =>
      (super.noSuchMethod(
            Invocation.method(#upsertItems, [items]),
            returnValue: _i7.Future<List<_i10.ItemDto>>.value(<_i10.ItemDto>[]),
          )
          as _i7.Future<List<_i10.ItemDto>>);

  @override
  _i7.Future<List<_i5.ParticipantDto>> listParticipants(String? billId) =>
      (super.noSuchMethod(
            Invocation.method(#listParticipants, [billId]),
            returnValue: _i7.Future<List<_i5.ParticipantDto>>.value(
              <_i5.ParticipantDto>[],
            ),
          )
          as _i7.Future<List<_i5.ParticipantDto>>);

  @override
  _i7.Future<_i5.ParticipantDto> upsertParticipant(_i5.ParticipantDto? dto) =>
      (super.noSuchMethod(
            Invocation.method(#upsertParticipant, [dto]),
            returnValue: _i7.Future<_i5.ParticipantDto>.value(
              _FakeParticipantDto_3(
                this,
                Invocation.method(#upsertParticipant, [dto]),
              ),
            ),
          )
          as _i7.Future<_i5.ParticipantDto>);

  @override
  _i7.Future<void> deleteParticipant(String? participantId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteParticipant, [participantId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>> createShareToken({
    required String? billId,
    required String? tokenHash,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createShareToken, [], {
              #billId: billId,
              #tokenHash: tokenHash,
            }),
            returnValue: _i7.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i7.Future<Map<String, dynamic>>);

  @override
  _i7.Future<void> revokeShareToken(String? tokenId) =>
      (super.noSuchMethod(
            Invocation.method(#revokeShareToken, [tokenId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<Map<String, dynamic>?> resolveShareToken(String? tokenHash) =>
      (super.noSuchMethod(
            Invocation.method(#resolveShareToken, [tokenHash]),
            returnValue: _i7.Future<Map<String, dynamic>?>.value(),
          )
          as _i7.Future<Map<String, dynamic>?>);

  @override
  _i7.Future<List<Map<String, dynamic>>> listTemplates() =>
      (super.noSuchMethod(
            Invocation.method(#listTemplates, []),
            returnValue: _i7.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i7.Future<List<Map<String, dynamic>>>);

  @override
  _i7.Future<String> createTemplateFromBill({
    required String? billId,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTemplateFromBill, [], {
              #billId: billId,
              #name: name,
            }),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#createTemplateFromBill, [], {
                  #billId: billId,
                  #name: name,
                }),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> instantiateTemplate(String? templateId) =>
      (super.noSuchMethod(
            Invocation.method(#instantiateTemplate, [templateId]),
            returnValue: _i7.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#instantiateTemplate, [templateId]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> deleteTemplate(String? templateId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTemplate, [templateId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<List<_i11.AssignmentDto>> listAssignments(String? billId) =>
      (super.noSuchMethod(
            Invocation.method(#listAssignments, [billId]),
            returnValue: _i7.Future<List<_i11.AssignmentDto>>.value(
              <_i11.AssignmentDto>[],
            ),
          )
          as _i7.Future<List<_i11.AssignmentDto>>);

  @override
  _i7.Future<List<_i11.AssignmentDto>> replaceAssignments(
    String? billId,
    List<_i11.AssignmentDto>? next,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#replaceAssignments, [billId, next]),
            returnValue: _i7.Future<List<_i11.AssignmentDto>>.value(
              <_i11.AssignmentDto>[],
            ),
          )
          as _i7.Future<List<_i11.AssignmentDto>>);
}

/// A class which mocks [OCRService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOCRService extends _i1.Mock implements _i12.OCRService {
  MockOCRService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.Result<_i13.OcrResponseDto>> processReceipt(
    List<_i14.Uint8List>? imagesBytes, {
    String? hint,
    String? currency,
    Map<String, String>? fingerprintHeaders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #processReceipt,
              [imagesBytes],
              {
                #hint: hint,
                #currency: currency,
                #fingerprintHeaders: fingerprintHeaders,
              },
            ),
            returnValue: _i7.Future<_i8.Result<_i13.OcrResponseDto>>.value(
              _i9.dummyValue<_i8.Result<_i13.OcrResponseDto>>(
                this,
                Invocation.method(
                  #processReceipt,
                  [imagesBytes],
                  {
                    #hint: hint,
                    #currency: currency,
                    #fingerprintHeaders: fingerprintHeaders,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i8.Result<_i13.OcrResponseDto>>);
}
